### ISSUE TITLE
An consultation to the R package BMA

### ISSUE THREAD

**Issue by dududurant** [hanase/BMA#7]
Hello. I would like to ask a question about the package BMA . I have a  simulation of linear regression and my candidate models are ten nested models .The first model only includes the first variable of design matrix X and the second one includes the first two variables,  and so on. The coefficient vector beta of full model  is a given vector which the elements are all fixed numbers.  Now I want to obtain their weights via Bayesian model averaging when I default all model prior is uniform. How can I achieve it? (In other words , I found the BMA is applicable to the model set of whole submodels but not the ten models I want. I just want it show me the posterior probability(or weights) of the ten models).

**Comment by adrianraftery** [comment]
It's true that the bicreg function doesn't allow you to do this directly. But you can do it manually pretty easily:

1. Compute BIC_k for each of the 10 models (k=1,...,10) using formula  (26) in Raftery (1995).
2. Form w_k = exp(-BIC_k / 2) for each model
3. Replace w_k by w_k / sum_{j=1}^10 w_j. Then w_k is the approximate posterior probability of model k.
4. Obtain BMA inference for the regression parameters using equations (36), (38), (39), and possibly (33), of Raftery (1995). This gives you the same output as the bicreg function.

Note: You can find a reprint of  Raftery (1995) at https://sites.stat.washington.edu/raftery/Research/PDF/socmeth1995.pdf
